# Based on https://github.com/wlonkly/dotfiles/blob/master/home/.config/starship.toml

add_newline = false

format = """[\
$python\
$username\
$hostname\
$directory\
$git_branch\
](cyan)\\$ """


[hostname]
ssh_only = false
format = "[@](white)[$hostname](green)"

[username]
style_user = "cyan"
style_root = "red bold"
format = "[$user]($style)"
show_always = true

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[:](white)[$path](yellow)"
truncation_symbol = "~/"

[git_branch]
format = " [$branch](purple)"
only_attached = true

[git_commit]
format = " [$hash](purple)"
only_detached = true

[git_state]
format = "[|$state:$progress_current/$progress_total](purple)"

# this is meant to work as closely as possible like
# github.com:magicmonty/bash-git-prompt
[git_status]
format = "[(\\[$conflicted$staged$modified$deleted$renamed$untracked$stashed$ahead_behind\\])]($white)"

ahead = "↑${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓${count}"

conflicted = "[ ✖$count✖ ](bold red)"
staged = "[✚$count](green)"
modified = "[✚$count](bold blue)"
deleted = "[-$count](red)"
renamed = "[»$count](green)"
untracked = "[??$count](cyan)"
stashed = "[⚑$count](bold blue)"

# only care about virtualenv
[python]
format = '[( \($virtualenv\))](yellow)'
